/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Autenticar usuário e obter token JWT */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Registrar novo usuário */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chat/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar sessões de chat do usuário autenticado */
        get: operations["listSessions"];
        put?: never;
        /** Criar nova sessão de chat */
        post: operations["createSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chat/sessions/{sessionId}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obter histórico de mensagens de uma sessão */
        get: operations["getMessages"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chat/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Enviar uma mensagem no chat */
        post: operations["sendMessage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chat/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Fazer upload de arquivo anexo (TXT ou PDF, máx 5MB) */
        post: operations["uploadFile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chat/files/{fileId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Baixar arquivo anexado */
        get: operations["downloadFile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Verificar saúde da aplicação */
        get: operations["healthCheck"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        LoginRequest: {
            /** @example admin */
            username: string;
            /**
             * Format: password
             * @example 123456
             */
            password: string;
        };
        LoginResponse: {
            /**
             * @description JWT token (HMAC-SHA256, expira em 24h)
             * @example eyJhbGciOiJIUzI1NiIs...
             */
            token: string;
            /**
             * @description Tempo de expiração em segundos
             * @example 86400
             */
            expiresIn: number;
        };
        RegisterRequest: {
            username: string;
            /** Format: password */
            password: string;
            /** Format: email */
            email?: string;
        };
        RegisterResponse: {
            /** Format: uuid */
            id: string;
            username: string;
            /** Format: date-time */
            createdAt: string;
        };
        SendMessageRequest: {
            /**
             * Format: uuid
             * @description ID da sessão de chat
             */
            chatSessionId: string;
            /** @description Conteúdo da mensagem (máx 10.000 caracteres) */
            content: string;
        };
        MessageResponse: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            chatSessionId: string;
            /** @enum {string} */
            role: "USER" | "ASSISTANT";
            content: string;
            /** Format: date-time */
            timestamp: string;
        };
        ChatSessionResponse: {
            /** Format: uuid */
            id: string;
            title: string;
            /** Format: date-time */
            createdAt: string;
        };
        FileUploadResponse: {
            /** Format: uuid */
            fileId: string;
            fileName: string;
            /** @description Tamanho do arquivo em bytes */
            fileSize: number;
            /** Format: date-time */
            uploadedAt: string;
        };
        ErrorResponse: {
            status: number;
            error: string;
            message: string;
            /** Format: date-time */
            timestamp: string;
        };
        /**
         * @description Status do documento no pipeline de ingestão RAG
         * @enum {string}
         */
        DocumentStatus: "PENDING" | "PROCESSING" | "COMPLETED" | "FAILED";
        DocumentResponse: {
            /** Format: uuid */
            id: string;
            fileName: string;
            fileSize: number;
            mimeType?: string;
            status: components["schemas"]["DocumentStatus"];
            errorMessage?: string | null;
            /** Format: date-time */
            uploadedAt: string;
            /** Format: date-time */
            processedAt?: string | null;
        };
        RagMessageResponse: components["schemas"]["MessageResponse"] & {
            /** @description Fontes utilizadas pelo RAG na resposta */
            sources?: components["schemas"]["DocumentResponse"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Login bem-sucedido */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description Credenciais inválidas */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Usuário cadastrado com sucesso */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegisterResponse"];
                };
            };
            /** @description Dados inválidos ou username já em uso */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listSessions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lista de sessões retornada com sucesso */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatSessionResponse"][];
                };
            };
            /** @description Não autenticado */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    createSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description Título da sessão */
                    title: string;
                };
            };
        };
        responses: {
            /** @description Sessão criada com sucesso */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatSessionResponse"];
                };
            };
            /** @description Dados inválidos */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Não autenticado */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getMessages: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID da sessão de chat */
                sessionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Histórico de mensagens retornado com sucesso */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"][];
                };
            };
            /** @description Não autenticado */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Sessão não encontrada */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    sendMessage: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SendMessageRequest"];
            };
        };
        responses: {
            /** @description Mensagem enviada com sucesso */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            /** @description Dados inválidos (ex: conteúdo vazio ou excede 10.000 caracteres) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Não autenticado */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Sessão não encontrada */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    uploadFile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /**
                     * Format: binary
                     * @description Arquivo .txt ou .pdf (tamanho máximo 5.242.880 bytes)
                     */
                    file: string;
                };
            };
        };
        responses: {
            /** @description Arquivo enviado com sucesso */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileUploadResponse"];
                };
            };
            /** @description Formato inválido (apenas TXT e PDF são aceitos) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Não autenticado */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Arquivo excede o limite de 5MB (5.242.880 bytes) */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    downloadFile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID do arquivo */
                fileId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Arquivo baixado com sucesso */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": string;
                };
            };
            /** @description Não autenticado */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Arquivo não encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    healthCheck: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Aplicação saudável */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example UP */
                        status: string;
                        /** Format: date-time */
                        timestamp: string;
                    };
                };
            };
        };
    };
}

// ── Backward-compatible aliases (flat export) ──
export type LoginRequest = components["schemas"]["LoginRequest"];
export type LoginResponse = components["schemas"]["LoginResponse"];
export type RegisterRequest = components["schemas"]["RegisterRequest"];
export type RegisterResponse = components["schemas"]["RegisterResponse"];
export type SendMessageRequest = components["schemas"]["SendMessageRequest"];
export type MessageResponse = components["schemas"]["MessageResponse"];
export type ChatSessionResponse = components["schemas"]["ChatSessionResponse"];
export type FileUploadResponse = components["schemas"]["FileUploadResponse"];
export type ErrorResponse = components["schemas"]["ErrorResponse"];
export type DocumentStatus = components["schemas"]["DocumentStatus"];
export type DocumentResponse = components["schemas"]["DocumentResponse"];
export type RagMessageResponse = components["schemas"]["RagMessageResponse"];
export type HealthResponse = {
    status: string;
    timestamp: string;
};
